name: OctoPerf Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  API_KEY: 59de8312-957c-4bda-a8dc-29802426db69

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run Octoperf task with Maven
        run: mvn octoperf:execute-scenario -DAPI_KEY=$API_KEY --file pom.xml
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: octoperf-result
          path: target/**
