# For more information on how to use our maven plugin, see:
# https://github.com/OctoPerf/octoperf-maven-plugin

name: OctoPerf Test using Github Actions

# Trigger an OctoPerf load test
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn octoperf:execute-scenario --file pom.xml
